// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdguywdemromogltoynn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kZ3V5d2RlbXJvbW9nbHRveW5uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MjQ4OTcsImV4cCI6MjA2NzMwMDg5N30.qvbkAcf6-3WbpPCHFvJr8KBjM8q1H2G8zdxM_G_n7xY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});